jigs/apps/puzzle/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',    
    url(r'^start/([\-a-f0-9]+)/$','puzzle.views.start_puzzle_session'),
    url(r'^([\-a-f0-9]+)/$', 'puzzle.views.workon_session', name='puzzle'),
    url(r'^([\-a-f0-9]+)/status/$', 'puzzle.views.session_status'),
)

jigs/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
    url(r'^$','views.home'),
    url(r'^puzzle/', include('puzzle.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

jigs/apps/puzzle/models.py
import UUIDField
from image_utils import create_thumbnail

from PIL import Image, ImageOps

from django.db import models,transaction
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.conf import settings

import os,shutil,random


class Puzzle(models.Model):
    guid = UUIDField.UUIDField(primary_key=True)
    image_path = models.CharField(max_length=255)

    directory = property(fget=lambda self: os.path.join(settings.MEDIA_ROOT, self.guid))
    
    def get_piece_paths(self):
        return [os.path.join(self.directory,"%s.jpg"%piece.pk) for piece in self.puzzlepiece_set.all()]

    def get_thumbnail_path(self, width=256, height=256):
        return os.path.join(os.path.split(self.directory)[1],
                            "%sx%s_%s" % (width, height, os.path.split(self.image_path)[1]))


class PuzzlePiece(models.Model):
    puzzle = models.ForeignKey(Puzzle)
    x = models.IntegerField()
    y = models.IntegerField()
    width = models.IntegerField(default=100)
    height = models.IntegerField(default=100)
    
    path = property(fget=lambda self:self.puzzle.guid+"/%s.jpg"%self.pk)


class PuzzleSession(models.Model):
    guid = UUIDField.UUIDField(primary_key=True)
    puzzle = models.ForeignKey(Puzzle)

    def create_session_dict(self):
        d = {}
        for sess_piece in self.puzzlesessionpiece_set.all():
            d[str(sess_piece.piece.pk)] = {"pos": (sess_piece.x, sess_piece.y),
                                           "size": (sess_piece.piece.width, sess_piece.piece.height),
                                           "locked_by": None,
                                           "path": sess_piece.piece.path}
        return d

    
class PuzzleSessionPiece(models.Model):
    session = models.ForeignKey(PuzzleSession)
    piece   = models.ForeignKey(PuzzlePiece)
    x = models.IntegerField()
    y = models.IntegerField()    


def start_session(puzzle):
    session = PuzzleSession(puzzle=puzzle)
    session.save()
    pieces = puzzle.puzzlepiece_set.all()
    possible_points = []    
    for piece in pieces:
        possible_points.append((piece.x,piece.y))
    
    for piece in pieces:
        x,y = random.choice(possible_points)
        session_piece = PuzzleSessionPiece(session=session,piece=piece,x=x,y=y)
        session_piece.save()
        possible_points.remove((x,y))
    return session


def create_puzzle(image_path,piece_width=500,piece_height=500):
    img = Image.open(image_path)
    w, h = piece_width,piece_height
    tiles_x, tiles_y = img.size[0]/w,img.size[1]/h

    with transaction.commit_on_success():
        puzzle = Puzzle()
        puzzle.save()
        guid = puzzle.guid

        piece_dir = puzzle.directory
        if not os.path.exists(piece_dir):
            os.makedirs(piece_dir)

        puzzle.image_path = os.path.join(os.path.split(puzzle.directory)[1],
                                         os.path.split(image_path)[1])
        # Save the original
        img.save(os.path.join(settings.MEDIA_ROOT, puzzle.image_path))
        # Create a thumbnail
        thumb = create_thumbnail(img)
        thumb.save(os.path.join(settings.MEDIA_ROOT,
                   puzzle.get_thumbnail_path()))

        for y in range(0, tiles_y):
            for x in range(0, tiles_x):
                left= x * w
                top = y * h
                right = x * w + w
                bottom = y * h + h
                region = img.crop((left, top, right, bottom))
                
                piece = PuzzlePiece(puzzle=puzzle, x=left, y=top, width=w, height=h)
                piece.save()
                region.save( os.path.join(piece_dir, "%s.jpg" % piece.pk))
        puzzle.save()
    return puzzle
                
@receiver(post_delete)
def delete_puzzle(sender, instance, **kwargs):
    if sender == Puzzle:
        if os.path.exists(instance.directory):
            shutil.rmtree(instance.directory)

jigs/apps/puzzle/views.py
from models import Puzzle,PuzzlePiece,PuzzleSession,start_session

from django.shortcuts import render_to_response, get_object_or_404,redirect
from django.http import HttpResponse,Http404
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.core.cache import cache
from django.core.urlresolvers import reverse

import json


def start_puzzle_session(request, guid):
    puzzle = get_object_or_404(Puzzle,guid=guid)
    session = start_session(puzzle)
    return redirect("%s?session=%s" % (reverse("puzzle", args=(guid,)),session.guid))


def session_key(session_guid):
    return "session-%s" % session_guid


def workon_session(request, guid):
    try:
        session_guid = request.GET['session']
        session_dict = cache.get(session_key(session_guid))
        if session_dict is None:
            session = get_object_or_404(PuzzleSession,guid=session_guid)
            session_dict = session.create_session_dict()

        context = RequestContext(request)
        context['session_data'] = session_dict
        context['session_guid'] = session_guid

        cache.set(session_key(session_guid), session_dict)
        return render_to_response("puzzle/puzzle_view.html",context_instance=context)
    except KeyError:
        return Http404()
        
@csrf_exempt        
def session_status(request, guid):
    try:
        data = json.loads(request.body)
    except:
        data = request.GET

    session_guid = data.get('session') or data.get('session')
    session_dict = cache.get(session_key(session_guid))
    if session_dict is None:
        session = get_object_or_404(PuzzleSession, guid=session_guid)
        session_dict = session.create_session_dict()

    try:
        context = RequestContext(request)
        
        if request.method == "POST":
            for key, value in data.items():
                if key.startswith("sessp"):
                    sp_id = key.replace("sessp","")
                    piece_dict = session_dict.get(sp_id)
                    if piece_dict:
                        print "Rewriting %s to %s" % (sp_id, value)
                        piece_dict["pos"] = (value[0], value[1])

        cache.set(session_key(session_guid), session_dict)
        return HttpResponse(json.dumps(session_dict),mimetype='application/json')
    except KeyError:
        return Http404()    

jigs/views.py
from puzzle.models import Puzzle,PuzzleSession

from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

def home(request):
    context = RequestContext(request)
    context['puzzles'] = Puzzle.objects.all()
    return render_to_response("jigs/index.html",context_instance=context)

jigs/apps/jigs_core/templates/jigs/index.html
<html>
    <head>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        <link href="{{ STATIC_URL }}css/puzzles.css" rel="stylesheet" />
        <title>Puzzles</title>
    </head>
    <body>
        <div class="container">
            <div class="page-header text-center">
                <h1>jigs</h1>
            </div>
        </div>
        <div class="container">
            {% for puzzle in puzzles %}
                {% cycle '<div class="row-fluid">' '' '' %}
                    <div class="puzzleContainer span3 {% cycle 'offset1' '' '' %}">
                        <img src="{{ MEDIA_URL }}{{ puzzle.get_thumbnail_path }}" class="puzzlePortrait img-polaroid">
                        <div class="sessionList well">
                            <ul class="nav nav-list">
                                <li class="nav-header">Sessions</li>
                                {%for sess in puzzle.puzzlesession_set.all%}
                                    <li><a href="/puzzle/{{puzzle.guid}}?session={{sess.guid}}">{{sess.guid}}</a></li>
                                {%endfor%}
                                <li class="divider"></li>
                                <li><a href="/puzzle/start/{{puzzle.guid}}">Start new session</a></li>
                            </ul>
                        </div>
                    </div>
                {% cycle '' '' '</div>' %}
            {% endfor %}
        </div>
    </body>
</html>

jigs/apps/puzzle/templates/puzzle/puzzle_view.html
<html>
    <head>
        <style>
            #puzzle{
                width:100%;
                height:100%;
                border:1px solid;
            }
        </style>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>        
        <script type="text/javascript">
            var pieces = [],pieceDict={},dirtyPieces=[],
                cvOrigin = [0,0],mouseStart=[0,0],mouseEnd=[0,0],mouseDown=false,
                zoom = 1,
                selectedObject=null;
            function puzzleUpdate()
            {
                var data = {
                    session:"{{session_guid}}"
                };
                if (true){
                    for (var i=0;i<dirtyPieces.length;i++){
                        var piece = dirtyPieces[i];
                        data["sessp"+piece.id] = [piece.offsetX,piece.offsetY];
                        dirtyPieces.pop();
                        i--;
                    }
                }

                $.ajax({
                  type: "POST",
                  url: "status/",
                  data: JSON.stringify(data),
                  success: function(json){
                        for (var piece_id in json){
                            if (!selectedObject || (selectedObject && piece_id != selectedObject.id)){
                                var updated_piece = json[piece_id];
                                pieceDict[piece_id].offsetX = updated_piece.pos[0];
                                pieceDict[piece_id].offsetY = updated_piece.pos[1];
                            }
                        }
                        Draw(puzzle);
                  },
                  dataType: "json"
                });
            }
            function Draw(canvas)
            {
                // Clear the canvas first
                canvas.width = canvas.width
                var ctx = canvas.getContext('2d');
                ctx.scale(zoom,zoom);
                ctx.translate(cvOrigin[0],cvOrigin[1]);
                for (var i=0;i<pieces.length;i++){
                    var piece = pieces[i];
                    ctx.drawImage(piece.image,piece.offsetX,piece.offsetY,piece.width,piece.height);
                    if (piece == selectedObject){
                        ctx.strokeStyle = '#ff0';
                    }else{
                        ctx.strokeStyle = '#000';
                    }
                    ctx.strokeRect(piece.offsetX,piece.offsetY,piece.width,piece.height);                    
                }
                
                for (var i=0;i<pieces.length;i++){
                    var piece = pieces[i];
                    ctx.fillStyle = '#ff0';
                    ctx.fillText(piece.id,piece.offsetX,piece.offsetY+40);
                }
            }
            $(document).ready(function(){
                var canvas = $("#puzzle")[0];

                {% for piece_id, data in session_data.items %}
                    var piece={};
                    piece.image = new Image();
                    piece.image.src = "/media/{{ data.path }}";
                    piece.id = {{ piece_id }};
                    piece.offsetX = {{ data.pos.0 }};
                    piece.offsetY = {{ data.pos.1 }};
                    piece.width = {{ data.size.0 }};
                    piece.height = {{ data.size.1 }};
                    pieceDict[{{ piece_id }}] = piece;
                    piece.image.onload = function(){
                        Draw(canvas);
                    }
                    pieces.push(piece);
                {%endfor%}

                $("#puzzle").mousedown(function (e)
                {    
                    var mouseXY = [e.pageX,e.pageY],
                        pieceHit = false,
                        x = mouseXY[0]/zoom,
                        y = mouseXY[1]/zoom;
                    mouseStart = mouseXY;
                    mouseDown = true;

                    if (e.button == 0){
                        for (var i=0;i<pieces.length;i++){
                            var piece = pieces[i],
                                bounds = [(cvOrigin[0]+piece.offsetX),(cvOrigin[1]+piece.offsetY),
                                          (cvOrigin[0]+piece.offsetX+piece.width),(cvOrigin[1]+piece.offsetY+piece.height)];
                            if (x >= bounds[0] && x <= bounds[2] &&
                                y >= bounds[1] && y <= bounds[3])
                                {
                                    pieceHit = true;
                                    selectedObject=piece;
                                    // Move piece to the end of the list so it gets drawn
                                    // on top.
                                    pieces.splice(i,1);
                                    pieces.push(selectedObject);
                                    Draw(canvas);
                                    break;
                                }
                        }
                    }
                    if (!pieceHit){
                        selectedObject = null;
                    }
                });
                $("#puzzle").mousemove(function (e)
                {
                    if (mouseDown){
                        var mouseXY = [e.pageX,e.pageY];
                        var diffX = mouseXY[0] - mouseStart[0];
                        var diffY = mouseXY[1] - mouseStart[1];
                        if (selectedObject) {
                            selectedObject.offsetX += diffX/zoom;
                            selectedObject.offsetY += diffY/zoom;

                            if (dirtyPieces.indexOf(selectedObject) < 0){
                                dirtyPieces.push(selectedObject)
                            }
                        }
                        else{
                            cvOrigin[0] += diffX*1.5/(zoom>0?zoom:1);
                            cvOrigin[1] += diffY*1.5/(zoom>0?zoom:1);
                        }
                        mouseStart = mouseXY;
                        Draw(canvas);
                    }
                });
                window.onmouseup = function (e)
                {
                    mouseDown = false;
                    selectedObject = null;
                    Draw(canvas)
                }
                canvas.onmousewheel = function(event){
                    var mousex = event.clientX - canvas.offsetLeft;
                    var mousey = event.clientY - canvas.offsetTop;
                    var wheel = event.wheelDelta/120;
                    if (event.wheelDelta > 0)
                    {
                        zoom *= 1.3;
                    }
                    else
                    {
                        zoom /= 1.3;
                    }
                    Draw(canvas);
                };
                
                window.addEventListener('resize', resizeCanvas, false);
                function resizeCanvas() {
                    canvas.width = window.innerWidth;
                    canvas.height = window.innerHeight;
                    Draw(canvas); 
                }
                resizeCanvas();
                window.setInterval(puzzleUpdate,100);
            });
        </script>
    </head>
    <body>
        <canvas id="puzzle"></canvas>
    </body>
</html>   